[package]
name = "cslice"
version = "0.3.0"
authors = ["Dave Herman <dherman@mozilla.com>"]
description = "A library of slices with a stable ABI for interfacing with C."
repository = "https://github.com/dherman/cslice"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/cslice"
